import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import  train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
u=LinearRegression()
df=pd.read_csv("insurance.csv")
female=pd.DataFrame(df[df["sex"] == "female"])
#print(female)
male=pd.DataFrame(df[df["sex"]=="male"])
#print(male)
#print(female["bmi"].max())
#print(female["bmi"].min())
#print(male["bmi"].max())
#print(male["bmi"].min())
x=female[female["smoker"]== "yes"]["smoker"].count()
#print(x)
#sns.countplot(female["children"])
#sns.countplot(male["children"])
#sns.countplot()
#plt.show()
cr=df.corr()
#sns.heatmap(cr,annot=True)
x=pd.DataFrame(df["age"])
y=pd.DataFrame(df["charges"])
#sns.jointplot(x,y,kind="reg")
#plt.show()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=4)
u.fit(x_train,y_train)
y_predict=u.predict(x_test)
scr=u.score(x_test,y_test)
print(scr)
err=mean_absolute_error(y_test,y_predict)
err2=mean_squared_error(y_test,y_predict)
err3=r2_score(y_test,y_predict)
print(err)
print(err2)
print(err3)
